name: Main Node.js Package

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "ojosdeserbio@gmail.com"
      - run: git config --global user.name "Emiliopg91"
      - run: npm install
      - run: npm version patch
      - run: npm run build
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: git push --follow-tags
      - run: git remote update
      - run: git fetch
      - run: git checkout --track origin/develop
      - run: git reset --hard main --
      - run: git push --force
      - run: packageName=$(npm run env | grep "npm_package_name" | awk -F "=" '{print $2}'
      - run: versionsToDrop=$(npm view decky-plugin-framework versions --json | grep '[[:digit:]].[[:digit:]].[[:digit:]]-[[:digit:]]' | sed 's/\"//g' | sed 's/,//g' | sed 's/[[:space:]]//g')
      - run: while IFS= read -r line; do npm unpublish $packageName@$line; done <<< "$versionsToDrop"        
